jukebox2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^transfer/', include('spotify_gmusic.urls', namespace='transfer')),
]

spotify_gmusic/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
				url(r'^$', views.index, name='index'),
				url(r'^authenticate/', views.authenticate, name='authenticate'),
				url(r'^auth_result/', views.process, name='process'),
				]

spotify_gmusic/models.py
from django.db import models

# Create your models here.

spotify_gmusic/views.py
import urllib.parse
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.urlresolvers import reverse
# from logic.util import *
client_id = '6846427bd95949cfa5b89ec4205d9606'
client_secret = 'fb0f8e63157146858d267dd0e93dffdd'
import random
def random_string(n):
	return ''.join([chr(random.randint(33,127)) for x in range(n)])
# Create your views here.
def index(request):
	return render(request, 'spotify_gmusic/index.html', {})

def authenticate(request):
	redirect_uri = settings.HOST_URL + reverse('transfer:process');
	print(redirect_uri)
	scope = 'user-read-private user-read-email playlist-read-private playlist-read-collaborative'
	auth_url = 'https://accounts.spotify.com/authorize?'
	sid = random_string(16)
	request.session['sid'] = sid
	auth_query = {'response_type' : 'code', 'client_id' : client_id, \
				'scope' : scope, 'redirect_uri' : redirect_uri, 'state' : sid}
	auth_url += urllib.parse.urlencode(auth_query)
	print(auth_url)
	return HttpResponseRedirect(auth_url)

def process(request):
	code, sid = request.GET.get('code'), request.GET.get('state')
	stored_sid = request.session.get('sid')
	if stored_sid != sid:
		print('State mismatch - try the whole process again.')
	token_url = 'https://accounts.spotify.com/api/token'
    # authOptions = {
    #   url: 'https://accounts.spotify.com/api/token',
    #   form: {
    #     code: code,
    #     redirect_uri: redirect_uri,
    #     grant_type: 'authorization_code'
    #   },
    #   headers: {
    #     'Authorization': 'Basic ' + (new Buffer(client_id + ':' + client_secret).toString('base64'))
    #   },
    #   json: true
    # };
	print(code, sid, stored_sid)
	print()
	print(request.GET)
	return render(request, 'spotify_gmusic/process_auth.html', {'code' : code, 'sid' : sid, 'stored_sid' : stored_sid})

spotify_gmusic/templates/spotify_gmusic/index.html
<!DOCTYPE html>
<head>
{% load staticfiles %}
<title>Index</title>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'spotify_gmusic/main.css' %}" />
</head>
<body>
<a href="{% url 'transfer:authenticate' %}">Click here to authenticate</a>
</body>

spotify_gmusic/templates/spotify_gmusic/process_auth.html
<!DOCTYPE html>
<head>
{% load staticfiles %}
<title>Processed Authentication!</title>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'spotify_gmusic/main.css' %}" />
</head>
<body>
<p>Code: {{ code }};</p>
<p>SID: {{sid}} </p>
<p>Stored SID: {{stored_sid}} </p>
</body>